
title: Eduardo Wanderley - Web Developer
email: wanderley.eduardo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Im making a website.
#baseurl: ""
url: "https://github.com/eduardowanderleyde/my-portfolio" 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#theme: minima
theme: minima
plugins:
  - jekyll-feed

sass:
  quiet_deps: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
