
title: Eduardo Wanderley - Web Developer
email: wanderley.eduardo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Im making a website.
#baseurl: ""
url: "https://github.com/eduardowanderleyde/my-portfolio" 
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#theme: minima
theme: minima
plugins:
  - jekyll-feed

sass:
  quiet_deps: true
